# Generated by Django 2.1.2 on 2018-11-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='', max_length=1)),
                ('dinner', models.CharField(choices=[('G1', 'Garden Salad'), ('G2', 'Greek Salad'), ('AP', 'Antipasto'), ('BZ', 'Baked Ziti'), ('MP', 'Meatball Parm'), ('CP', 'Chicken Parm')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.ForeignKey(on_delete='models.SET_NULL', related_name='dinner_add', to='orders.DinnerPlatters')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(choices=[('M2', 'Baked Ziti w/ Mozzarella'), ('M1', 'Baked Ziti w/ Meatballs'), ('C1', 'Baked Ziti w/ Chicken')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=3)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.CharField(choices=[('G1', 'Garden Salad'), ('G2', 'Greek Salad'), ('AP', 'Antipasto'), ('ST', 'Salad w/ Tuna')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.CharField(choices=[('C1', 'Cheese'), ('C2', 'Cheeseburger'), ('C3', 'Chicken Parmigiana'), ('E1', 'Eggplant Parmigiana'), ('E2', 'Extra Cheese on any subs'), ('F1', 'Fried Chicken'), ('H1', 'Ham + Cheese'), ('H2', 'Hamburger'), ('I1', 'Italian'), ('M1', 'Meatball'), ('S1', 'Sausage, Peppers & Onions'), ('S2', 'Steak'), ('S3', 'Steak + Cheese'), ('S4', 'Steak + Green Peppers'), ('S5', 'Steak + Mushrooms'), ('S6', 'Steak + Onions'), ('T1', 'Tuna'), ('T2', 'Turkey'), ('V1', 'Veggie')], default='', max_length=3)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('A1', 'Anchovies'), ('A2', 'Artichoke'), ('B1', 'Barbecue Chicken'), ('B2', 'Black Olives'), ('B3', 'Buffalo Chicken'), ('C1', 'Canadian Bacon'), ('E1', 'Eggplant'), ('F1', 'Fresh Garlic'), ('G1', 'Green Peppers'), ('H1', 'Ham'), ('H2', 'Hamburger'), ('M1', 'Mushrooms'), ('O1', 'Onions'), ('P1', 'Pepperoni'), ('P2', 'Pineapple'), ('S1', 'Sausage'), ('S2', 'Spinach'), ('T1', 'Tomato & Basil'), ('Z1', 'Zucchini')], default='', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pasta',
            field=models.ForeignKey(on_delete='models.SET_NULL', related_name='pasta_add', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='p', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_size',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='p_size', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ForeignKey(on_delete='models.SET_NULL', related_name='salad_add', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ForeignKey(on_delete='models.SET_NULL', related_name='subs_add', to='orders.Subs'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(on_delete='models.SET_NULL', related_name='topping_add', to='orders.Toppings'),
        ),
    ]
