# Generated by Django 2.1.2 on 2018-10-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
                ('toppings', models.CharField(max_length=60)),
                ('additions', models.CharField(max_length=60)),
            ],
        ),
    ]
