# Generated by Django 2.1.2 on 2018-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1, null=True)),
                ('type', models.CharField(blank=True, choices=[('GARDEN', 'Garden Salad'), ('GREEK', 'Greek Salad'), ('APASTO', 'Antipasto'), ('ZITI', 'Baked Ziti'), ('MEAT', 'Meatball Parm'), ('CHICKEN', 'Chicken Parm')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='dinners', to='orders.DinnerPlatter')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(blank=True, choices=[('MOZZA', 'Baked Ziti w/ Mozzarella'), ('MEAT', 'Baked Ziti w/ Meatballs'), ('CHICKEN', 'Baked Ziti w/ Chicken')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REG', 'Regular'), ('SIC', 'Sicilian')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.CharField(blank=True, choices=[('GARDEN', 'Garden Salad'), ('GREEK', 'Greek Salad'), ('APASTO', 'Antipasto'), ('TUNA', 'Salad w/ Tuna')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1, null=True)),
                ('sub', models.CharField(blank=True, choices=[('CHEESE', 'Cheese'), ('CHEESEB', 'Cheeseburger'), ('CHICKEN', 'Chicken Parmigiana'), ('EGGPLANT', 'Eggplant Parmigiana'), ('XCHEESE', 'Extra Cheese on any subs'), ('FCHICKEN', 'Fried Chicken'), ('HAMC', 'Ham + Cheese'), ('HAMBURGER', 'Hamburger'), ('ITALIAN', 'Italian'), ('MEAT', 'Meatball'), ('SAPEON', 'Sausage, Peppers & Onions'), ('STEAK', 'Steak'), ('STEAKC', 'Steak + Cheese'), ('STEAKG', 'Steak + Green Peppers'), ('STEAKM', 'Steak + Mushrooms'), ('STEAKO', 'Steak + Onions'), ('TUNA', 'Tuna'), ('TURKEY', 'Turkey'), ('VEGGIE', 'Veggie')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(blank=True, choices=[('ANCHOVY', 'Anchovies'), ('ARTICHOKE', 'Artichoke'), ('BACHICKEN', 'Barbecue Chicken'), ('BOLIVE', 'Black Olives'), ('BUCHICKEN', 'Buffalo Chicken'), ('CBACON', 'Canadian Bacon'), ('EGGPLANT', 'Eggplant'), ('FGARLIC', 'Fresh Garlic'), ('GPEPPER', 'Green Peppers'), ('HAM', 'Ham'), ('HAMBURGER', 'Hamburger'), ('MUSHROOM', 'Mushrooms'), ('ONION', 'Onions'), ('PEPPERONI', 'Pepperoni'), ('PINEAPPLE', 'Pineapple'), ('SAUSAGE', 'Sausage'), ('SPINACH', 'Spinach'), ('TOMATOBASIL', 'Tomato & Basil'), ('ZUCCHINI', 'Zucchini')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='pastas', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='pizzas', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='salads', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='subs', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='toppings', to='orders.Topping'),
        ),
    ]
