# Generated by Django 2.1.2 on 2018-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='demon', max_length=60),
            preserve_default=False,
        ),
    ]
