# Generated by Django 2.1.2 on 2018-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='type',
            field=models.CharField(blank=True, choices=[('GARDEN SALAD', 'Garden Salad'), ('GREEK SALAD', 'Greek Salad'), ('ANTIPASTO', 'Antipasto'), ('BAKED ZITI', 'Baked Ziti'), ('MEAT PARM', 'Meatball Parm'), ('CHICKEN PARM', 'Chicken Parm')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='pasta',
            field=models.CharField(blank=True, choices=[('BZ MOZZARELLA', 'Baked Ziti w/ Mozzarella'), ('BZ MEATBALLS', 'Baked Ziti w/ Meatballs'), ('BZ CHICKEN', 'Baked Ziti w/ Chicken')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=5),
        ),
        migrations.AlterField(
            model_name='salad',
            name='salad',
            field=models.CharField(blank=True, choices=[('GARDEN', 'Garden Salad'), ('GREEK', 'Greek Salad'), ('ANTIPASTO', 'Antipasto'), ('TUNA', 'Salad w/ Tuna')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEESE', 'Cheese'), ('CHEESEBURGER', 'Cheeseburger'), ('CHICKEN PARM', 'Chicken Parmigiana'), ('EGGPLANT PARM', 'Eggplant Parmigiana'), ('XCHEESE', 'Extra Cheese on any subs'), ('FRIED CHICKEN', 'Fried Chicken'), ('HAM_CHEESE', 'Ham + Cheese'), ('HAMBURGER', 'Hamburger'), ('ITALIAN', 'Italian'), ('MEATBALL', 'Meatball'), ('SAPEON', 'Sausage, Peppers & Onions'), ('STEAK', 'Steak'), ('STEAK_CHEESE', 'Steak + Cheese'), ('STEAK_GPEPPERS', 'Steak + Green Peppers'), ('STEAK_MUSHROOMS', 'Steak + Mushrooms'), ('STEAK_ONIONS', 'Steak + Onions'), ('TUNA', 'Tuna'), ('TURKEY', 'Turkey'), ('VEGGIE', 'Veggie')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(blank=True, choices=[('ANCHOVIES', 'Anchovies'), ('ARTICHOKE', 'Artichoke'), ('BARBECUE CHICKEN', 'Barbecue Chicken'), ('BLACK OLIVES', 'Black Olives'), ('CHEESE', 'Cheese'), ('BUFFALO CHICKEN', 'Buffalo Chicken'), ('CANADIAN BACON', 'Canadian Bacon'), ('EGGPLANT', 'Eggplant'), ('FRESH GARLIC', 'Fresh Garlic'), ('GREEN PEPPERS', 'Green Peppers'), ('HAM', 'Ham'), ('HAMBURGER', 'Hamburger'), ('MUSHROOMS', 'Mushrooms'), ('ONIONS', 'Onions'), ('PEPPERONI', 'Pepperoni'), ('PINEAPPLE', 'Pineapple'), ('SAUSAGE', 'Sausage'), ('SPINACH', 'Spinach'), ('TOMATO_BASIL', 'Tomato & Basil'), ('ZUCCHINI', 'Zucchini'), ('SPECIAL', 'Special')], max_length=60, null=True),
        ),
    ]
