# Generated by Django 2.1.2 on 2018-11-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181102_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='dinner_add', to='orders.DinnerPlatters'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='pasta_add', to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='salad',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='salad_add', to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='subs_add', to='orders.Subs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='topping_add', to='orders.Toppings'),
        ),
    ]
