# Generated by Django 2.1.2 on 2018-11-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181102_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dinner_size',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.SET_NULL', related_name='dinner_size_add', to='orders.DinnerPlatters'),
        ),
    ]
